### ISSUE TITLE
Plugin Install Failing

### ISSUE THREAD

**Issue by jimmypewtress** [bugfender/cordova-plugin-bugfender#11]
Hi

Cordova 11.0.0

On attempting to install the plugin using `cordova plugin add cordova-plugin-bugfender --variable BUGFENDER_APP_KEY=[APP_KEY] --variable BUGFENDER_AUTOMATIC=UI,CRASH`

It fails with

`Failed to install 'cordova-plugin-bugfender': CordovaError: Using "requireCordovaModule" to load non-cordova module "semver" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at getConfigParser (/Users/../../plugins/cordova-plugin-bugfender/scripts/check_ios_target.js:20:23)
    at module.exports (/Users/../../plugins/cordova-plugin-bugfender/scripts/check_ios_target.js:7:24)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:136:12)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:108:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Using "requireCordovaModule" to load non-cordova module "semver" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Any ideas?

**Comment by jimmypewtress** [comment]
Same behaviour if I roll back to Cordova 10.0.0

**Comment by jgimenez** [comment]
Hi @jimmypewtress , this module has been tested with Cordova 10, it should work there. Are you sure the output is the same?
Not sure about Cordova 11.

**Comment by jimmypewtress** [comment]
Hi @jgimenez, thanks for the response.  I took Bugfender out of the build I was needing to do so I could ship it.

I've just tried reinstalling the plugin to the project again and it worked straight away.  With Cordova 11 as well.

As far as I'm aware I've not changed anything else so not sure why it has decided to work this time but there you go.  Will close the issue.

**Comment by jgimenez** [comment]
Thanks for the update! Our engineers are already looking into it anyway. We'll see if this can be improved.

**Comment by jgimenez** [comment]
Following up on this, it seems [we're already using require() to load semver](https://github.com/bugfender/cordova-plugin-bugfender/blob/master/scripts/check_ios_target.js#L3).
