### ISSUE TITLE
Android app fails to launch.

### ISSUE THREAD

**Issue by mley** [bugfender/cordova-plugin-bugfender#15]
I followed along the steps to install the cordova-plugin-bugfender. Since it's an ionic/capacitor application, I had to install the plugin with
`npm install -s cordova-plugin-bugfender`
and add the API key and configuration to my capacitor.config.ts

```
cordova: {
    preferences: {
      BUGFENDER_APP_KEY: '...',
      BUGFENDER_AUTOMATIC: 'ALL',
    },
  },
```

When I run the application on an Android phone with `ionic cap run android` it instantly terminates with the following error stacktrace in `adb logcat`:

```
01-31 09:00:16.942 23503 23503 E AndroidRuntime: android.content.res.Resources$NotFoundException: String resource ID #0x0
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.content.res.Resources.getText(Resources.java:512)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:605)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.content.Context.getString(Context.java:766)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at com.bugfender.sdk.cordova.BugfenderPlugin.pluginInitialize(BugfenderPlugin.java:32)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at org.apache.cordova.PluginManager.init(PluginManager.java:86)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:58)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1303)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8603)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4191)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8741)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
01-31 09:00:16.942 23503 23503 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Ionic Angular 6.1
Capacitor 3.7

Do you have any clue what's going on and how I can fix it?

**Comment by jgimenez** [comment]
Hi @mley , for a Capacitor project, you can use the Capacitor plugin: https://github.com/bugfender/bugfender-web-capacitor

**Comment by mley** [comment]
that GitHub project does not seem to be public at this moment...

**Comment by jgimenez** [comment]
I see! You should be able to see it now
